- name: Docker
  hosts: docker_hosts
  become: true
  gather_facts: true


  tasks:

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: true
    
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        state: latest
      ignore_errors: true

    - name: update and start docker compose
      community.docker.docker_compose_v2:
        project_src: /docker/appdata
        pull: always
        state: present
        recreate: auto
        remove_orphans: yes


    - name: Remove unused docker images
      community.docker.docker_prune:
        images: yes
