- name: Docker
  hosts: docker_hosts
  become: True

  vars_files:
    - vault.yaml

  vars:
    ansible_user: "{{ user3 }}"
    ansible_become_pass: "{{ passw_docker }}"


  tasks:

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: True
    
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        state: latest
      ignore_errors: True

    - name: update and start docker compose
      community.docker.docker_compose_v2:
        project_src: /docker/appdata
        pull: always
        state: present
        recreate: auto
        remove_orphans: yes


    - name: Remove unused docker images
      community.docker.docker_prune:
        images: yes
