# playbooks 1 nuc

- name: proxmox
  hosts: nuc
  become: True

  vars_files:
    - vault.yaml
    
  vars:
    ansible_user: "{{ user1 }}"
    ansible_become_pass: "{{ passw_nuc }}"


  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: True
    
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        state: latest
      ignore_errors: True