# playbooks 1 nuc

- name: proxmox
  hosts: nuc
  become: true
  gather_facts: true


  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
      ignore_errors: true
    
    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: full
        state: latest
      ignore_errors: true